<?php

require __DIR__ . '/vendor/autoload.php';
$app = require_once __DIR__ . '/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

function quoteValue($value)
{
    if ($value === null) {
        return 'NULL';
    }
    if (is_bool($value)) {
        return $value ? 'TRUE' : 'FALSE';
    }
    if (is_int($value) || is_float($value)) {
        return (string)$value;
    }
    $escaped = str_replace("'", "''", $value);
    return "'{$escaped}'";
}

$tables = DB::select('SELECT tablename FROM pg_tables WHERE schemaname = current_schema() ORDER BY tablename');
$tableNames = array_map(fn($row) => $row->tablename, $tables);
$exportFile = __DIR__ . '/database/exports/seed_data_export.sql';
@mkdir(dirname($exportFile), 0777, true);

$fp = fopen($exportFile, 'w');
if (!$fp) {
    fwrite(STDERR, "Unable to open export file: {$exportFile}\n");
    exit(1);
}

fwrite($fp, "-- SQL export generated by export_seed_data.php\n");
fwrite($fp, "BEGIN;\n\n");

foreach ($tableNames as $tableName) {
    $rows = DB::table($tableName)->get();
    if ($rows->isEmpty()) {
        continue;
    }
    $columns = array_keys((array)$rows->first());
    fwrite($fp, "-- Table: {$tableName}\n");
    fwrite($fp, "TRUNCATE TABLE \"{$tableName}\" RESTART IDENTITY CASCADE;\n");
    foreach ($rows as $row) {
        $values = array_map(fn($col) => quoteValue($row->$col), $columns);
        $columnsList = implode(', ', array_map(fn($col) => "\"{$col}\"", $columns));
        $valuesList = implode(', ', $values);
        fwrite($fp, "INSERT INTO \"{$tableName}\" ({$columnsList}) VALUES ({$valuesList});\n");
    }
    fwrite($fp, "\n");
}

fwrite($fp, "COMMIT;\n");
fclose($fp);

echo "Export written to: {$exportFile}\n";
